### ISSUE TITLE
Ruch i ataki

### ISSUE THREAD

**Issue by bartek5186** [Dzejkk/My3DGameGH#1]
- Anulowanie Ataku

Anulowanie ataku niech zadziała w ten sposób, że zamiast całkowicie resetować animację, 
animacja ta powraca z miejsca w którym została zakończona np. klikając drugi raz, niech odpali się
reverse animacji z miejsca w którym kończysz cios (może być przyspieszony)

- Dodatkowe blokowanie podczas ataku -

W momencie wykonywania ataku, należy zablokować obrót myszką (lewo / prawo)

- Obrażenia przeciwnika

Zadawanie obrażeń powinno działać jedynie podczas wykonywania ataku, obecnie można przejść przez postać zadając jej obrażenia bez ataku

- Synchronizacja animacji z podłożem oraz szybkością poruszania się

Szybkość animacji oraz poruszania się (do przodu, tyłu, w boki...) powinna działać tak, żeby wizualnie wyglądało realnie tj.
szybkość poruszania się, szybkość wykonywania danej animacji powinna być dobrana tak, żeby nie było efektu "ślizgania" się po powierzchni.

- Dodatkowa animacja podczas obracania myszką (lewo prawo) gdy postać stoi

Podczas obracania myszką gdy postać jest w stanie idle i chcesz ją obrócić w lewo / prawo, powinna być animacja obrotu (są takie na mixamo).

**Comment by Dzejkk** [comment]
Tutaj na razie zrobiłem to blokowanie podczas ataku i przeciwnik dostaje obrażenia tylko, gdy wykonuje się atak.
