### ISSUE TITLE
Dźwięki

### ISSUE THREAD

**Issue by bartek5186** [Dzejkk/My3DGameGH#3]
Podczas animacji ataku, kiedy miecz dotyka celu - uruchom dźwięk uderzenia:
- jeśli to jest typ character enemy - to dźwięki uderzenia miecza:
a) o postać bez dźwięku postaci np. uderzenie w zbroję, w szatę
b) Dźwięki odbierania obrażeń przez postać atakowaną - wydawaną przez postać tj. dźwięk typu "ała" ;P
- najlepiej mieć kilka takich dźwięków np 3. Randomowo wybierając jeden z nich
c) Dźwięk umierania postaci
d) Dźwięk machnięcia szablą
e) Dźwięk kopnięcia

**Comment by Dzejkk** [comment]
Dodałem dźwięki, ale na razie randomowo wybiera tylko umieranie wroga, bo pozostałych udało mi się znaleźć tylko 1 rodzaj.
